name: Question
description: Ask a question about UniDash
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation first:
        https://OWNER.github.io/UniDash/

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: I would like to know...
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What area is your question about?
      options:
        - Installation / Setup
        - Configuration
        - Usage
        - Development
        - Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about your question.
    validations:
      required: false

  - type: checkboxes
    id: docs-checked
    attributes:
      label: Documentation Check
      description: Please confirm you have checked the documentation.
      options:
        - label: I have checked the documentation and could not find an answer.
          required: true
